apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
  namespace: finsecure-banking
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS messages (
        id SERIAL PRIMARY KEY,
        author VARCHAR(255) NOT NULL,
        content TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
  namespace: finsecure-banking
spec:
  template:
    spec:
      containers:
      - name: db-init
        image: postgres:13-alpine
        command: 
        - /bin/bash
        - -c
        - |
          until pg_isready -h database-service -p 5432 -U postgres; do
            echo "Waiting for database..."
            sleep 2
          done
          echo "Database is ready!"
          psql -h database-service -U postgres -d messages -f /docker-entrypoint-initdb.d/init.sql
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-script
        configMap:
          name: db-init-script
      restartPolicy: OnFailure
  backoffLimit: 3