apiVersion: v1
kind: Namespace
metadata:
  name: finsecure-banking
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: finsecure-banking
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres (base64 encoded)
  password: cGFzc3dvcmQ=  # password (base64 encoded)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: finsecure-banking
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path  # k3d default storage class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-logs-pvc
  namespace: finsecure-banking
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path